export const ACTION_KEYWORDS = new Set([
    "FIRE",
    "TELEPORT",
    "SHIELD",
    "CLOAK",
    "DASH",
    "MINE",
    "TAUNT",
    "MOVE",
    "STOP",
    "MOVE_FAST",
    "BACKUP",
    "BURST_FIRE",
    "LEAD_FIRE",
    "PATHFIND",
]);
