import type { SceneScript } from '../sceneScriptEngine';

export const ARRAY_SCRIPTS: Record<string, SceneScript> = {
  'arr-01': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'arr-02': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'idle' } },
    ],
  },
  'arr-03': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'arr-04': {
    loop: true,
    phases: [
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'idle' } },
    ],
  },
  'arr-05': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'moveTo', x: 0.25, y: 0.25 } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  25, action: { type: 'moveTo', x: 0.75, y: 0.25 } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  25, action: { type: 'moveTo', x: 0.75, y: 0.75 } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  25, action: { type: 'moveTo', x: 0.25, y: 0.75 } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  25, action: { type: 'idle' } },
    ],
  },
  'arr-06': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'arr-07': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'idle' } },
    ],
  },
  'arr-08': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'idle' } },
    ],
  },
  'arr-09': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'burst' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'arr-10': {
    loop: true,
    phases: [
      { ticks:  15, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'burst' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
};
