import type { SceneScript } from '../sceneScriptEngine';

export const CONDITIONAL_SCRIPTS: Record<string, SceneScript> = {
  'cond-01': {
    loop: true,
    phases: [
      { ticks: 80, action: { type: 'moveTo', x: 0.6875, y: 0.5 } },
      { ticks: 10, action: { type: 'idle' } },
      { ticks: 80, action: { type: 'moveTo', x: 0.5,    y: 0.5 } },
      { ticks: 10, action: { type: 'idle' } },
    ],
  },
  'cond-02': {
    loop: true,
    phases: [
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'scan' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'cond-03': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'cond-04': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  12, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'cond-05': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  30, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'cond-06': {
    loop: true,
    phases: [
      { ticks:  40, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'cond-07': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  35, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'cond-08': {
    loop: true,
    phases: [
      { ticks:  35, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'cond-09': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'cond-10': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
};
