import type { SceneScript } from '../sceneScriptEngine';

export const DATA_STRUCTURE_SCRIPTS: Record<string, SceneScript> = {
  'ds-01': {
    loop: true,
    phases: [
      { ticks:  40, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'ds-02': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'burst' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'burst' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'ds-03': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'ds-04': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  30, action: { type: 'moveTo', x: 0.65, y: 0.40 } },
      { ticks:  10, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  30, action: { type: 'moveTo', x: 0.35, y: 0.60 } },
      { ticks:  10, action: { type: 'burst' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'ds-05': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'ds-06': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'burst' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'ds-07': {
    loop: true,
    phases: [
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'ds-08': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'ds-09': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'burst' } },
      { ticks:  40, action: { type: 'idle' } },
    ],
  },
  'ds-10': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
};
