import type { SceneScript } from '../sceneScriptEngine';

export const GRAPH_THEORY_SCRIPTS: Record<string, SceneScript> = {
  'gfx-01': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'gfx-02': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'gfx-03': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  36, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'gfx-04': {
    loop: true,
    phases: [
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'gfx-05': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'gfx-06': {
    loop: true,
    phases: [
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  22, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  22, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  22, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  22, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'gfx-07': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  36, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'gfx-08': {
    loop: true,
    phases: [
      { ticks:  15, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  15, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  12, action: { type: 'burst' } },
      { ticks:  15, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'gfx-09': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'gfx-10': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'rotate', angle: -0.3 } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'rotate', angle: 0.3 } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'rotate', angle: -0.3 } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'rotate', angle: 0.3 } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  24, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
};
