import type { SceneScript } from '../sceneScriptEngine';

export const LOOP_SCRIPTS: Record<string, SceneScript> = {
  'loop-01': {
    loop: true,
    phases: [
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'loop-02': {
    loop: true,
    phases: [
      { ticks:  40, action: { type: 'moveTo', x: 0.25, y: 0.50 } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveTo', x: 0.75, y: 0.50 } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'idle' } },
    ],
  },
  'loop-03': {
    loop: true,
    phases: [
      { ticks:  60, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  60, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'idle' } },
    ],
  },
  'loop-04': {
    loop: true,
    phases: [
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'idle' } },
    ],
  },
  'loop-05': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'moveTo', x: 0.25, y: 0.20 } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'moveTo', x: 0.75, y: 0.20 } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'moveTo', x: 0.75, y: 0.80 } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'moveTo', x: 0.25, y: 0.80 } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'idle' } },
    ],
  },
  'loop-06': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'loop-07': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'loop-08': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'idle' } },
    ],
  },
  'loop-09': {
    loop: true,
    phases: [
      { ticks:  15, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'loop-10': {
    loop: true,
    phases: [
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  12, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  12, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
};
