import { Suggestion } from './types';

export const LINE_HEIGHT = 20;

export const AUTOCOMPLETE_SUGGESTIONS: Suggestion[] = [
    // Commands
    { label: 'MOVE', detail: 'command', hint: 'Move forward at standard speed' },
    { label: 'MOVE_FAST', detail: 'command', hint: 'Move forward at 2× speed' },
    { label: 'STOP', detail: 'command', hint: 'Halt all movement' },
    { label: 'BACKUP', detail: 'command', hint: 'Move in reverse' },
    { label: 'PATHFIND', detail: 'command', hint: 'A* pathfind toward target' },
    { label: 'FIRE', detail: 'command', hint: 'Single shot at nearest enemy' },
    { label: 'BURST_FIRE', detail: 'command', hint: 'Multi-shot burst at enemy' },
    { label: 'SCAN', detail: 'command', hint: 'Rotate FOV cone +15°' },
    { label: 'WAIT', detail: 'command', hint: 'Pause execution for N ticks' },
    // Control Flow
    { label: 'IF', detail: 'control', hint: 'Conditional branch' },
    { label: 'WHILE', detail: 'control', hint: 'Loop while condition is true' },
    { label: 'FUNCTION', detail: 'control', hint: 'Define a reusable function' },
    { label: 'CALL', detail: 'control', hint: 'Call a function by name' },
    { label: 'SET', detail: 'control', hint: 'Assign a variable' },
    // Queries
    { label: 'GET_HEALTH()', detail: 'query', hint: 'Print health to logs' },
    { label: 'GET_ENERGY()', detail: 'query', hint: 'Print energy to logs' },
    { label: 'GET_ENERGY_PCT()', detail: 'query', hint: 'Print energy % to logs' },
    { label: 'GET_DISTANCE()', detail: 'query', hint: 'Print nearest enemy distance' },
    { label: 'GET_POSITION()', detail: 'query', hint: 'Print current {x, y} position' },
    { label: 'GET_ROTATION()', detail: 'query', hint: 'Print body facing angle' },
    { label: 'GET_FOV_DIR()', detail: 'query', hint: 'Print scanner facing angle' },
    { label: 'GET_VISIBLE_COUNT()', detail: 'query', hint: 'Print # enemies in FOV' },
    { label: 'GET_OBSTACLE_TYPE()', detail: 'query', hint: 'Print type of nearest obstacle' },
    { label: 'GET_OBSTACLE_DISTANCE()', detail: 'query', hint: 'Print distance to nearest obstacle' },
    // Identifiers (readable)
    { label: 'rotation', detail: 'identifier', hint: 'Body facing angle (radians). Writable.' },
    { label: 'angle', detail: 'identifier', hint: 'Alias for rotation' },
    { label: 'rot', detail: 'identifier', hint: 'Alias for rotation' },
    { label: 'fovDirection', detail: 'identifier', hint: 'Scanner facing angle (radians). Independent from body.' },
    { label: 'lockVision', detail: 'flag', hint: 'SET to TRUE to lock scanner to body rotation' },
    { label: 'energy', detail: 'identifier', hint: 'Alias – use MY_ENERGY' },
    { label: 'distance', detail: 'identifier', hint: 'Distance to nearest VISIBLE enemy' },
    { label: 'health', detail: 'identifier', hint: 'Current robot HP (0–100)' },
    { label: 'MY_ENERGY', detail: 'identifier', hint: 'Current energy (0–1000)' },
    { label: 'ENERGY_PCT', detail: 'identifier', hint: 'Energy as percentage (0–100)' },
    { label: 'IN_STASIS', detail: 'identifier', hint: 'True when energy ≤ 0' },
    { label: 'CAN_SEE_ENEMY', detail: 'identifier', hint: 'True if enemy is in FOV cone' },
    { label: 'spotted', detail: 'identifier', hint: 'Alias for CAN_SEE_ENEMY' },
    { label: 'NEAREST_VISIBLE_X', detail: 'identifier', hint: 'X of nearest visible enemy' },
    { label: 'NEAREST_VISIBLE_Y', detail: 'identifier', hint: 'Y of nearest visible enemy' },
    { label: 'CAN_SEE_OBSTACLE', detail: 'identifier', hint: 'True if obstacle is in FOV cone' },
    { label: 'NEAREST_OBSTACLE_TYPE', detail: 'identifier', hint: 'Type of nearest obstacle ("SOLID", "TRAP", etc)' },
    { label: 'NEAREST_OBSTACLE_DISTANCE', detail: 'identifier', hint: 'Distance to nearest visible obstacle' },
    { label: 'VISIBLE_ENEMY_COUNT', detail: 'identifier', hint: 'Number of enemies currently in FOV cone' },
    // Math Standard Library
    { label: 'ABS(x)', detail: 'math', hint: 'Absolute value of x' },
    { label: 'SQRT(x)', detail: 'math', hint: 'Square root of x (clamps negatives to 0)' },
    { label: 'POW(base, exp)', detail: 'math', hint: 'Raise base to the power of exp' },
    { label: 'SIN(x)', detail: 'math', hint: 'Sine of x (radians)' },
    { label: 'COS(x)', detail: 'math', hint: 'Cosine of x (radians)' },
    { label: 'TAN(x)', detail: 'math', hint: 'Tangent of x (radians)' },
    { label: 'ATAN2(y, x)', detail: 'math', hint: 'Angle in radians from origin to point (x, y). Use for aiming.' },
    { label: 'MIN(a, b)', detail: 'math', hint: 'Smaller of two values' },
    { label: 'MAX(a, b)', detail: 'math', hint: 'Larger of two values' },
    { label: 'FLOOR(x)', detail: 'math', hint: 'Round x down to nearest integer' },
    { label: 'CEIL(x)', detail: 'math', hint: 'Round x up to nearest integer' },
    { label: 'ROUND(x)', detail: 'math', hint: 'Round x to nearest integer' },
    { label: 'LOG(x)', detail: 'math', hint: 'Natural logarithm of x (x must be > 0)' },
    { label: 'RANDOM()', detail: 'math', hint: 'Random float between 0.0 and 1.0' },
    // Array Operations
    { label: 'LENGTH(arr)', detail: 'array', hint: 'Number of elements in array (or characters in string)' },
    { label: 'PUSH(arr, value)', detail: 'array', hint: 'Append value to end of array. Returns new length.' },
    { label: 'POP(arr)', detail: 'array', hint: 'Remove and return last element of array' },
    // Advanced Sensors (Phase 1)
    { label: 'GET_ALL_VISIBLE_ENEMIES()', detail: 'sensor', hint: 'Returns Array of snapshots: each is [dist, x, y, health]. Unsorted — implement your own sort!' },
    { label: 'RAYCAST(angle)', detail: 'sensor', hint: 'Fire invisible laser at relative angle (radians). Returns distance to first hit: wall, SOLID obstacle, or robot.' },
    // Dictionaries (Phase 2)
    { label: '{}', detail: 'dictionary', hint: 'Object Literal for State Machines. e.g. { mode: "HUNT" }' },
    { label: 'obj.key', detail: 'dictionary', hint: 'Dot notation property access / mutation' },
    { label: 'obj["key"]', detail: 'dictionary', hint: 'Bracket notation dynamic indexing' },
    // Swarm Intelligence (Phase 3)
    { label: 'BROADCAST(data)', detail: 'swarm', hint: 'Send dictionary/array/string to all alive teammates. Returns recipient count.' },
    { label: 'RECEIVE()', detail: 'swarm', hint: 'Returns Array of all messages received since last tick. Clears inbox after read.' },
];

export const DETAIL_COLORS: Record<string, string> = {
    command:    '#22d3ee',
    control:    '#f59e0b',
    identifier: '#a855f7',
    flag:       '#4ade80',
    query:      '#06b6d4',
    math:       '#f97316',
    array:      '#818cf8',
    sensor:     '#ec4899',
    dictionary: '#f43f5e',
    swarm:      '#34d399',
};
