// ─────────────────────────────────────────────────────────────────────────────
// SceneScripts — per-level phase-based enemy behaviour configs.
//
// Each SceneScript encodes the enemy robot's choreography as a sequence of
// phases (action + duration), designed to visually demonstrate the problem
// concept described in the level brief.
//
// All loops are 180-360 ticks (3-6 seconds at 60 fps).
// ─────────────────────────────────────────────────────────────────────────────
import type { SceneScript } from './sceneScriptEngine';

export const SCRIPTS: Record<string, SceneScript> = {

  // ── Conditionals ──────────────────────────────────────────────────────────

  'cond-01': {
    loop: true,
    phases: [
      { ticks:  45, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  70, action: { type: 'moveTo', x: 0.50, y: 0.50 } },
      { ticks:  35, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },

  'cond-02': {
    loop: true,
    phases: [
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'rotate', angle: -0.6 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'rotate', angle: 0.6 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'rotate', angle: -0.6 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'rotate', angle: 0.6 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },

  'cond-03': {
    loop: true,
    phases: [
      { ticks:  40, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'cond-04': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveTo', x: 0.55, y: 0.50 } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'cond-05': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'idle' } },
    ],
  },

  'cond-06': {
    loop: true,
    phases: [
      { ticks:  50, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  50, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'idle' } },
    ],
  },

  'cond-07': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'cond-08': {
    loop: true,
    phases: [
      { ticks:  40, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'cond-09': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:  35, action: { type: 'moveTo', x: 0.65, y: 0.45 } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveTo', x: 0.75, y: 0.50 } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'cond-10': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'idle' } },
    ],
  },

  // ── Loops ─────────────────────────────────────────────────────────────────

  'loop-01': {
    loop: true,
    phases: [
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  12, action: { type: 'idle' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  12, action: { type: 'idle' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  12, action: { type: 'idle' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  12, action: { type: 'idle' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },

  'loop-02': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },

  'loop-03': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },

  'loop-04': {
    loop: true,
    phases: [
      // Round 1
      { ticks:  15, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      // Round 2
      { ticks:  15, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      // Round 3
      { ticks:  15, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },

  'loop-05': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  30, action: { type: 'moveTo', x: 0.75, y: 0.50 } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'loop-06': {
    loop: true,
    phases: [
      // Outer loop iteration 1
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      // Outer loop iteration 2
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      // Outer loop iteration 3
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },

  'loop-07': {
    loop: true,
    phases: [
      { ticks:  35, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  35, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'loop-08': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },

  'loop-09': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'loop-10': {
    loop: true,
    phases: [
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  35, action: { type: 'idle' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  // ── Arrays ────────────────────────────────────────────────────────────────

  'arr-01': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'moveTo', x: 0.55, y: 0.35 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveTo', x: 0.65, y: 0.35 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveTo', x: 0.55, y: 0.55 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveTo', x: 0.65, y: 0.55 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveTo', x: 0.60, y: 0.45 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveTo', x: 0.75, y: 0.50 } },
    ],
  },

  'arr-02': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'arr-03': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'rotate', angle: -0.4 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'rotate', angle: 0.4 } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'rotate', angle: -0.4 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'rotate', angle: 0.4 } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'arr-04': {
    loop: true,
    phases: [
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'idle' } },
    ],
  },

  'arr-05': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'moveTo', x: 0.55, y: 0.50 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveTo', x: 0.65, y: 0.50 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveTo', x: 0.55, y: 0.50 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveTo', x: 0.70, y: 0.50 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveTo', x: 0.75, y: 0.50 } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'arr-06': {
    loop: true,
    phases: [
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'arr-07': {
    loop: true,
    phases: [
      { ticks:  15, action: { type: 'moveTo', x: 0.55, y: 0.35 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.65, y: 0.35 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.55, y: 0.50 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.65, y: 0.50 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.55, y: 0.65 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.65, y: 0.65 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.60, y: 0.50 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'arr-08': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'arr-09': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },

  'arr-10': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },

  // ── Data Structures ───────────────────────────────────────────────────────

  'ds-01': {
    loop: true,
    phases: [
      { ticks:  50, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  50, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'idle' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  50, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
      { ticks:  50, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'ds-02': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'ds-03': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'ds-04': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'ds-05': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'ds-06': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'ds-07': {
    loop: true,
    phases: [
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'ds-08': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  'ds-09': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'idle' } },
    ],
  },

  'ds-10': {
    loop: true,
    phases: [
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },

  // ── Recursion ─────────────────────────────────────────────────────────────

  'rec-01': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  28, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'rec-02': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:  28, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'rec-03': {
    loop: true,
    phases: [
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  22, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  22, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  22, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'rec-04': {
    loop: true,
    phases: [
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  24, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  24, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  34, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  34, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'rec-05': {
    loop: true,
    phases: [
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'rec-06': {
    loop: true,
    phases: [
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  24, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  24, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  34, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  34, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'rec-07': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'idle' } },
    ],
  },

  'rec-08': {
    loop: true,
    phases: [
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'rec-09': {
    loop: true,
    phases: [
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'rec-10': {
    loop: true,
    phases: [
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  // ── Graph Theory ──────────────────────────────────────────────────────────

  'gfx-01': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'gfx-02': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'gfx-03': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  36, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'gfx-04': {
    loop: true,
    phases: [
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'gfx-05': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'gfx-06': {
    loop: true,
    phases: [
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  28, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  28, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'gfx-07': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  18, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  36, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'gfx-08': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'gfx-09': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },

  'gfx-10': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'rotate', angle: -0.3 } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'rotate', angle: 0.3 } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'rotate', angle: -0.3 } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'rotate', angle: 0.3 } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'rotate', angle: -0.3 } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'burst' } },
      { ticks:  24, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
};
