export const CATEGORY_COLORS: Record<string, string> = {
  'Control Flow': 'var(--docs-orange)',
  Movement: 'var(--docs-green)',
  Vision: 'var(--docs-cyan)',
  Sensors: 'var(--docs-cyan-dark)',
  Attack: 'var(--docs-orange)',
  Tactics: 'var(--docs-yellow)',
  'Advanced Combat': 'var(--docs-red)',
  Evasion: 'var(--docs-emerald)',
  Intelligence: 'var(--docs-purple)',
  Energy: 'var(--docs-indigo)',
  FOV: 'var(--docs-cyan)',
  Scan: 'var(--docs-cyan)',
  Self: 'var(--docs-slate)',
  Combat: 'var(--docs-red)',
  flag: 'var(--docs-green)',
  Math: 'var(--docs-orange)',
  Arrays: 'var(--docs-indigo)',
  'Advanced Sensors': 'var(--docs-pink)',
  'Vision Array': 'var(--docs-pink)',
  'Line of Sight': 'var(--docs-rose)',
  'Swarm Comm': 'var(--docs-emerald)',
  Swarm: 'var(--docs-emerald)',
};
